services:
 app:
   image: node:19-alpine
   working_dir: /usr/src/app
   volumes: 
     - .:/usr/src/app
   env_file:
     - .env
   ports:
     - '${PUERTO}:${PUERTO}'  # Exponiendo el puerto de la app
   depends_on:
     - bd-server  # Asegura que la base de datos se inicie antes que la app
   command: 'npm run start:dev'
   networks:
     - my-network

 my-sql:
    image: mysql:8.0.39-debian
    # container_name: mysql-dev
    ports:
      - "DB_PORT:DB_PORT"
    environment:
      MYSQL_ROOT_PASSWORD: clave123
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql  # Para persistencia de datos
  # Exponiendo el puerto del contenedor MySQL en tu máquina
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
