services:
  #  Servicio API para la aplicación NestJS
  api:
    image: "backendgrupo5/grupo-5-backend:${VERSION_TAG}"        
    environment:   
      DB_TYPE: ${DB_TYPE}                   
      DB_HOST: ${DB_HOST}                   
      DB_PORT: ${DB_PORT}                   
      DB_USER: ${DB_USER}                   
      DB_PASS_ROOT: ${DB_PASS_ROOT}         
      DB_NAME: ${DB_NAME}                   
      NESTJS_PORT: ${NESTJS_PORT}   
      NODE_ENV: ${NODE_ENV}                 # Entorno de ejecución de la API              
    ports:
      - "5001:${NESTJS_PORT}"               
    depends_on:
      - db                                  
    networks:
      - backend_network 

  # Servicio de Base de Datos MySQL
  db:
    image: "mysql:${DB_VERSION}"           
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS_ROOT} 
      MYSQL_DATABASE: ${DB_NAME}           
    volumes:
      - .mysql_data:/var/lib/mysql         
    ports:
      - "5002:${DB_PORT}"                  

    networks:
      - backend_network                    

  # Migración de Base de Datos
  flyway:
    image: flyway/flyway:10.20.1-alpine
    volumes:
    - ./Scripts_SQL:/flyway/sql
    command: 
      -url=jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?allowPublicKeyRetrieval=true
      -user=${DB_USER}  
      -password=${DB_PASS_ROOT}  
      -connectRetries=60  migrate 
    depends_on:
      - db
    networks:
      - backend_network                   

# Definimos las redes
networks:
  backend_network:
    driver: bridge

# Define volúmenes persistentes para almacenamiento de datos
volumes:
  .mysql_data:
    driver: local                           

