services:
  app: 
    image: backendgrupo5/grupo-5-backend:1.0.0
    env_file:
      - .env-produccion
    ports:
      - '${PORT}:${PORT}'
  
  bd-server:
    image:
      - mysql:8.0.39-debian
    environment:
      - MYSQL_ROOT_PASSWORD='${PASSDB}'
    env_file:
      - .env-produccion
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '${PORTDB}:${PORTDB}'
